[theme]
base = "dark"
primaryColor = "#FFCA28"                # Kuning
backgroundColor = "#121212"             # Abu gelap
secondaryBackgroundColor = "#1E1E1E"    # Abu kehitaman
textColor = "#FFFFFF"
font = "sans serif"